projectVersion=0.1.0
groupName=io.github.gauravshukla092
projectName=unified-api-client
javaVersion=21

gradleEnterpriseVersion=3.20.2
restAssuredVersion=6.0.0
slf4jVersion=2.0.17
logbackVersion=1.5.20
jacksonVersion=2.18.2
junitVersion=5.10.2
# Build optimization
org.gradle.jvmargs= -Xmx4g -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.console=rich
org.gradle.workers.max=4


org.gradle.test.maxParallelForks=2
